version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: gunicorn app.wsgi --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    user: "django_user"
    environment:
      - DJANGO_DEBUG=0
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DOMAIN}

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-front
    ports:
      - 3000:3000
    volumes:
      - front_build:/app/build

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf #:ro at the end?
      - front_build:/var/www/frontend    #/usr/share/nginx/html
    depends_on:
      - backend
      - frontend

volumes:
  front_build: