FROM node:21-alpine

ENV NODE_ENV development

WORKDIR /app

COPY frontend/safari_soul/ /app

RUN npm install
RUN npm run build
# EXPOSE 3000
# CMD ["npm", "run", "build"]

# CMD [ "npm", "run", "dev" ]

# FROM node:21-alpine AS build-stage
# WORKDIR /app
# COPY safari_soul/package*.json .
# RUN npm ci
# COPY  safari_soul/ /app
# RUN npm run build
# RUN npm prune --production

# FROM node:21-alpine
# WORKDIR /app
# COPY --from=build-stage /app/build build/
# COPY --from=build-stage /app/node_modules node_modules/
# COPY safari_soul/package.json .
# EXPOSE 3000
# ENV NODE_ENV=production
# CMD [ "node", "build" ]

