# Generated by Django 4.2.5 on 2023-11-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safari', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturalattraction',
            name='date',
        ),
    ]
