# Generated by Django 4.2.5 on 2023-11-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safari', '0003_rename_date_destinations_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinations',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='destinations',
            name='duration_nights',
        ),
        migrations.RemoveField(
            model_name='destinations',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='tourpackages',
            name='end_date',
        ),
        migrations.AddField(
            model_name='tourpackages',
            name='duration_days',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tourpackages',
            name='duration_nights',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
