# Generated by Django 4.2.5 on 2023-11-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safari', '0004_remove_destinations_duration_days_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destinations',
            new_name='Destination',
        ),
        migrations.RenameModel(
            old_name='TourPackages',
            new_name='TourPackage',
        ),
    ]
