# Generated by Django 4.2.5 on 2023-11-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safari', '0005_rename_destinations_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
