# Generated by Django 4.2.5 on 2023-11-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safari', '0006_destination_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['-created_at']},
        ),
    ]
