# Generated by Django 4.2.5 on 2023-11-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safari', '0008_alter_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='start_date',
            field=models.DateField(),
        ),
    ]
